services:
  ida:
    image: ${APP_IMAGE}
    restart: unless-stopped

    volumes:
      - ./data:/db_data
      - /opt/platform/public/ida/static:/static_data
      - /opt/platform/public/ida/media:/media_data
      - ./logs:/log_data

    env_file:
      - app.env

    environment:
      - DJANGO_ENVIRONMENT=production
      - DJANGO_STATIC_ROOT=/static_data
      - DJANGO_MEDIA_ROOT=/media_data
      - DJANGO_DATABASE_NAME=/db_data/db.sqlite3
      - DJANGO_LOG_FILENAME=/log_data/ida.log
      - DJANGO_DEBUG=0
      - DJANGO_PROJECT_STATIC_DIR=/app/static

    networks:
      web-proxy:
        aliases:
          - ida

networks:
  web-proxy:
    external: true
