# Generated by Django 5.1.6 on 2025-04-29 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('phone', models.CharField(blank=True, default='', help_text='Phone number with country code (eg. +32 490 12 34 56)', max_length=255, verbose_name='phone')),
                ('email', models.EmailField(blank=True, default='', max_length=255, verbose_name='email')),
                ('website', models.URLField(blank=True, default='', max_length=255, verbose_name='website')),
                ('vat_number', models.CharField(blank=True, default='', max_length=255, verbose_name='VAT number')),
                ('business_court', models.CharField(blank=True, default='', help_text='Example: Antwerpen, afd. Hasselt', max_length=255, verbose_name='business court')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/', verbose_name='logo')),
                ('graphic_element', models.ImageField(blank=True, null=True, upload_to='companies/graphic_elements/', verbose_name='graphic element')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=34, verbose_name='IBAN')),
                ('bic', models.CharField(blank=True, default='', max_length=11, verbose_name='BIC')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'bank account',
                'verbose_name_plural': 'bank accounts',
            },
        ),
    ]
