# Generated by Django 5.1.6 on 2025-02-22 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, default='', help_text='Phone number with country code (eg. +32 490 12 34 56)', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=255)),
                ('website', models.URLField(blank=True, default='', max_length=255)),
                ('vat_number', models.CharField(blank=True, help_text='VAT number', max_length=255)),
                ('business_court', models.CharField(help_text='Business court (eg. Antwerpen, afd. Hasselt)', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=34)),
                ('bic', models.CharField(blank=True, default='', max_length=11)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
        ),
    ]
