# Generated by Django 5.1.6 on 2025-02-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='business_court',
            field=models.CharField(blank=True, default='', help_text='Business court (eg. Antwerpen, afd. Hasselt)', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='vat_number',
            field=models.CharField(blank=True, default='', help_text='VAT number', max_length=255),
        ),
    ]
