# Generated by Django 5.1.6 on 2025-02-28 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_business_court_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'verbose_name': 'bank account', 'verbose_name_plural': 'bank accounts'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'company', 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bic',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='bic'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='iban',
            field=models.CharField(max_length=34, verbose_name='iban'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='business_court',
            field=models.CharField(blank=True, default='', help_text='Example: Antwerpen, afd. Hasselt', max_length=255, verbose_name='business court'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=255, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Phone number with country code (eg. +32 490 12 34 56)', max_length=255, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='company',
            name='vat_number',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='VAT number'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, default='', max_length=255, verbose_name='website'),
        ),
    ]
