# Generated by Django 5.1.6 on 2025-02-28 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_alter_bankaccount_options_alter_company_options_and_more'),
        ('relations', '0002_alter_relation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, default='', max_length=255, verbose_name='number')),
                ('date', models.DateField(verbose_name='date')),
                ('date_due', models.DateField(blank=True, verbose_name='date due')),
                ('payment_communication', models.CharField(blank=True, default='', max_length=255, verbose_name='payment communication')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='company')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relations.relation', verbose_name='relation')),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='unit price')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='quantity')),
                ('vat_percentage', models.DecimalField(decimal_places=2, help_text='VAT Percentage', max_digits=5, verbose_name='VAT')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoice', verbose_name='invoice')),
            ],
            options={
                'verbose_name': 'invoice item',
                'verbose_name_plural': 'invoice items',
            },
        ),
    ]
