# Generated by Django 5.1.6 on 2025-04-30 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('relations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=10, verbose_name='number')),
                ('date', models.DateField(verbose_name='date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('sent', 'Sent'), ('paid', 'Paid')], default='draft', editable=False, max_length=10, verbose_name='status')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices', verbose_name='PDF file')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='company')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relations.relation', verbose_name='relation')),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='unit price')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='quantity')),
                ('vat_percentage', models.DecimalField(decimal_places=2, help_text='VAT percentage', max_digits=5, verbose_name='VAT')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoice', verbose_name='invoice')),
            ],
            options={
                'verbose_name': 'invoice item',
                'verbose_name_plural': 'invoice items',
            },
        ),
    ]
