# Generated by Django 5.1.6 on 2025-02-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_due',
            field=models.DateField(editable=False, verbose_name='date due'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(editable=False, max_length=255, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_communication',
            field=models.CharField(editable=False, max_length=255, verbose_name='payment communication'),
        ),
    ]
