# Generated by Django 5.1.6 on 2025-03-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_invoice_date_due_alter_invoice_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, help_text='VAT percentage', max_digits=5, verbose_name='VAT'),
        ),
    ]
