# Generated by Django 5.1.6 on 2025-03-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_invoiceitem_vat_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='date_due',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='payment_communication',
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices', verbose_name='PDF file'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('sent', 'Sent'), ('paid', 'Paid')], default='draft', editable=False, max_length=10, verbose_name='status'),
        ),
    ]
