# Generated by Django 5.1.6 on 2025-03-20 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_remove_invoice_date_due_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'permissions': [('send_invoice', 'Can send invoice to customers')], 'verbose_name': 'invoice', 'verbose_name_plural': 'invoices'},
        ),
    ]
