# Generated by Django 5.1.6 on 2025-03-20 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_alter_invoice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'invoice', 'verbose_name_plural': 'invoices'},
        ),
    ]
