# Generated by Django 5.1.6 on 2025-03-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_alter_invoice_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(editable=False, max_length=10, verbose_name='number'),
        ),
    ]
