# Generated by Django 5.1.6 on 2025-06-03 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('guard_service_duration', models.IntegerField(default=168, help_text='Expressed in hours, defaults to a week (168 hours).', verbose_name='guard service hours')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relations.relation', verbose_name='relation')),
                ('users', models.ManyToManyField(blank=True, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='users')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.CharField(choices=[('hour', 'Hourly'), ('day', 'Daily')], default='hour', max_length=20, verbose_name='interval')),
                ('frequency', models.CharField(choices=[('week', 'Weekly'), ('month', 'Monthly'), ('year', 'Yearly')], default='month', max_length=20, verbose_name='frequency')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'invoice settings',
                'verbose_name_plural': 'invoice settings',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimesheetSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.CharField(choices=[('hour', 'Hourly'), ('day', 'Daily')], default='hour', max_length=20, verbose_name='interval')),
                ('frequency', models.CharField(choices=[('week', 'Weekly'), ('month', 'Monthly'), ('year', 'Yearly')], default='month', max_length=20, verbose_name='frequency')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'timesheet settings',
                'verbose_name_plural': 'timesheet settings',
                'abstract': False,
            },
        ),
    ]
