# Generated by Django 5.2.5 on 2025-11-11 20:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('relations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('invoice_line_prefix', models.CharField(help_text="Prefix for invoice lines, e.g. 'IT-Service'", max_length=50, verbose_name='invoice line prefix')),
                ('company', models.ForeignKey(help_text='The company that executes work for this project', on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='company')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relations.relation', verbose_name='relation')),
                ('users', models.ManyToManyField(blank=True, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='users')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.IntegerField(choices=[(1, 'Standard'), (2, 'On call'), (3, 'Night'), (4, 'Saturday'), (5, 'Sunday'), (6, 'Other')], verbose_name='item type')),
                ('rate_type', models.IntegerField(choices=[(1, 'Daily'), (2, 'Hourly'), (3, 'Monthly')], default=2, verbose_name='rate type')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=Decimal('21'), help_text='VAT percentage', max_digits=5, verbose_name='VAT')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'project rate',
                'verbose_name_plural': 'project rates',
                'unique_together': {('project', 'item_type')},
            },
        ),
    ]
