# Generated by Django 5.1.6 on 2025-08-02 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetsettings',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='guard_service_duration',
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('standard', 'Standard'), ('on_call', 'On call'), ('night', 'Night'), ('saturday', 'Saturday'), ('sunday', 'Sunday'), ('other', 'Other')], max_length=50, verbose_name='item type')),
                ('rate_type', models.CharField(choices=[('daily', 'Daily'), ('hourly', 'Hourly'), ('monthly', 'Monthly')], default='hourly', max_length=20, verbose_name='rate type')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='projects.project')),
            ],
            options={
                'verbose_name': 'project rate',
                'verbose_name_plural': 'project rates',
                'unique_together': {('project', 'item_type')},
            },
        ),
        migrations.DeleteModel(
            name='InvoiceSettings',
        ),
        migrations.DeleteModel(
            name='TimesheetSettings',
        ),
    ]
