# Generated by Django 5.1.6 on 2025-08-02 17:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_timesheetsettings_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('21'), help_text='VAT percentage', max_digits=5, verbose_name='VAT'),
        ),
    ]
