# Generated by Django 5.1.6 on 2025-08-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rate_vat_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='invoice_line_prefix',
            field=models.CharField(default='IT-Service', help_text="Prefix for invoice lines, e.g. 'IT-Service'", max_length=50, verbose_name='invoice line prefix'),
            preserve_default=False,
        ),
    ]
