# Generated by Django 5.1.6 on 2025-08-03 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('projects', '0004_project_invoice_line_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(default=1, help_text='The company that executes work for this project', on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='company'),
            preserve_default=False,
        ),
    ]
