# Generated by Django 5.1.6 on 2025-08-03 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='project'),
        ),
    ]
