# Generated by Django 5.2.5 on 2025-10-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='item_type',
            field=models.IntegerField(choices=[(1, 'Standard'), (2, 'On call'), (3, 'Night'), (4, 'Saturday'), (5, 'Sunday'), (6, 'Other')], verbose_name='item type'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate_type',
            field=models.IntegerField(choices=[(1, 'Daily'), (2, 'Hourly'), (3, 'Monthly')], default=2, verbose_name='rate type'),
        ),
    ]
