# Generated by Django 5.2.5 on 2025-10-20 18:01

from django.db import migrations

SQL = """
UPDATE projects_rate
SET item_type = CASE item_type
  WHEN 'standard' THEN 1
  WHEN 'on_call'  THEN 2
  WHEN 'night'    THEN 3
  WHEN 'saturday' THEN 4
  WHEN 'sunday'   THEN 5
  WHEN 'other'    THEN 6
  ELSE item_type
END,
rate_type = CASE rate_type
  WHEN 'daily'   THEN 1
  WHEN 'hourly'  THEN 2
  WHEN 'monthly' THEN 3
  ELSE rate_type
END;
"""

REVERSE_SQL = """
UPDATE projects_rate
SET item_type = CASE CAST(item_type AS INTEGER)
  WHEN 1 THEN 'standard'
  WHEN 2 THEN 'on_call'
  WHEN 3 THEN 'night'
  WHEN 4 THEN 'saturday'
  WHEN 5 THEN 'sunday'
  WHEN 6 THEN 'other'
  ELSE item_type
END,
rate_type = CASE CAST(rate_type AS INTEGER)
  WHEN 1 THEN 'daily'
  WHEN 2 THEN 'hourly'
  WHEN 3 THEN 'monthly'
  ELSE rate_type
END;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0008_alter_rate_item_type_alter_rate_rate_type"),
    ]

    operations = [
        migrations.RunSQL(SQL, reverse_sql=REVERSE_SQL),
    ]
