"""Django settings for ida project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import json
from pathlib import Path

import envyronment as env
from django.utils.translation import gettext_noop

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
ROOT_DIR = BASE_DIR.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.read("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.read("DJANGO_DEBUG", True, astype=env.to_bool)

ALLOWED_HOSTS = env.read("DJANGO_ALLOWED_HOSTS", [], astype=json.loads)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "apps.companies",
    "apps.geo",
    "apps.relations",
    "apps.invoices",
    "apps.users",
    "apps.timesheets",
    "apps.projects",
    "django_telegram_app",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.auth.middleware.LoginRequiredMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "apps.users.middleware.UserLanguageMiddleware",
]

ROOT_URLCONF = "ida.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ida.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": env.read("DJANGO_DATABASE_NAME", ROOT_DIR / "db.sqlite3", astype=Path),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

# Languages we provide translations for, out of the box.
# Full list of language codes supported by Django can be found here:
# https://docs.djangoproject.com/en/5.1/ref/settings/#languages
LANGUAGES = [
    ("de", gettext_noop("German")),
    ("en", gettext_noop("English")),
    ("fr", gettext_noop("French")),
    ("nl", gettext_noop("Dutch")),
]

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = env.read("DJANGO_STATIC_ROOT", ROOT_DIR / "staticfiles", astype=Path)  # output for collectstatic
STATICFILES_DIRS = [env.read("DJANGO_PROJECT_STATIC_DIR", ROOT_DIR / "static", astype=Path)]

# Media files (user-uploaded files)
# https://docs.djangoproject.com/en/5.1/topics/files/#managing-files

MEDIA_URL = "media/"
MEDIA_ROOT = env.read("DJANGO_MEDIA_ROOT", ROOT_DIR / "media", astype=Path)

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Email settings
# https://docs.djangoproject.com/en/5.1/topics/email/#module-django.core.mail

EMAIL_BACKEND = env.read("DJANGO_EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = env.read("DJANGO_EMAIL_HOST", "localhost")
EMAIL_PORT = env.read("DJANGO_EMAIL_PORT", 25, astype=int)
EMAIL_USE_TLS = env.read("DJANGO_EMAIL_USE_TLS", False, astype=env.to_bool)
EMAIL_HOST_USER = env.read("DJANGO_EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = env.read("DJANGO_EMAIL_HOST_PASSWORD", "")

# CSRF settings
# https://docs.djangoproject.com/en/5.1/ref/settings/#csrf-trusted-origins
CSRF_TRUSTED_ORIGINS = env.read("DJANGO_CSRF_TRUSTED_ORIGINS", [], astype=json.loads)

# Logging settings
# https://docs.djangoproject.com/en/5.1/topics/logging/
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "file": {
            "level": env.read("DJANGO_FILE_LOG_LEVEL", "INFO"),
            "class": "logging.FileHandler",
            "filename": env.read(
                "DJANGO_LOG_FILENAME", ROOT_DIR / "logs" / "ida.log", astype=env.to_filepath, convert_default=True
            ),
        },
        "console": {
            "level": env.read("DJANGO_CONSOLE_LOG_LEVEL", "DEBUG"),
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["file", "console"],
            "level": env.read("DJANGO_LOG_LEVEL", "DEBUG"),
            "propagate": True,
        },
    },
}

AUTH_USER_MODEL = "users.IdaUser"

# Custom settings

ADMIN = {
    "SITE_HEADER": env.read("ADMIN_SITE_HEADER", "IDA Administration"),
    "ROOT_URL": env.read("ADMIN_ROOT_URL", "admin/"),
}

TELEGRAM = {
    "BOT_URL": env.read("TELEGRAM_BOT_URL"),
    "WEBHOOK_TOKEN": env.read("TELEGRAM_WEBHOOK_TOKEN"),
    "ROOT_URL": env.read("TELEGRAM_ROOT_URL", "telegram/"),
    "WEBHOOK_URL": env.read("TELEGRAM_WEBHOOK_URL", "webhook"),
}

DOMAIN_NAME = env.read("DJANGO_DOMAIN_NAME", "http://localhost:8000")
