# Generated by Django 5.1.6 on 2025-04-30 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('month', models.IntegerField(verbose_name='month')),
                ('year', models.IntegerField(verbose_name='year')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], default='draft', max_length=50, verbose_name='status')),
                ('only_weekdays', models.BooleanField(blank=True, default=True, verbose_name='only weekdays')),
                ('send_reminder', models.BooleanField(blank=True, default=True, verbose_name='send reminder')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relations.relation', verbose_name='relation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='TimesheetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('standard', 'Standard'), ('on_call', 'On call'), ('night', 'Night'), ('saturday', 'Saturday'), ('sunday', 'Sunday'), ('other', 'Other')], default='standard', max_length=50)),
                ('date', models.DateField()),
                ('worked_hours', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheets.timesheet')),
            ],
        ),
    ]
