# Generated by Django 5.1.6 on 2025-06-03 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('timesheets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='relation',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='user',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timesheetitem',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='timesheetitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='timesheetitem',
            name='item_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('on_call', 'On call'), ('night', 'Night'), ('saturday', 'Saturday'), ('sunday', 'Sunday'), ('other', 'Other')], default='standard', max_length=50, verbose_name='item type'),
        ),
        migrations.AlterField(
            model_name='timesheetitem',
            name='timesheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheets.timesheet', verbose_name='timesheet'),
        ),
        migrations.AlterField(
            model_name='timesheetitem',
            name='worked_hours',
            field=models.FloatField(verbose_name='worked hours'),
        ),
    ]
