# Generated by Django 5.1.6 on 2025-06-03 22:12

import django.db.models.deletion
from django.db import migrations, models


def create_default_othermodel(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    Relation = apps.get_model("relations", "Relation")
    Company = apps.get_model("companies", "Company")
    relation, _created = Relation.objects.get_or_create(id=1, defaults={"name": "Dummy Relation", "category": "CUSTOMER"})
    company_defaults = {
        "name": "IDA Inc.",
        "phone": "+32 490 12 34 56",
        "email": "info@ida.com",
        "website": "https://ida.com",
        "vat_number": "BE0123456789",
        "business_court": "Antwerpen, afd. Tongeren",
    }
    company, _created = Company.objects.get_or_create(id=1, defaults=company_defaults)
    defaults = {
        "name": "Dummy Project",
        "description": "A project for testing purposes",
        "start_date": "2025-01-01",
        "end_date": "2025-12-31",
        "relation": relation,
        "company": company,
        "invoice_line_prefix": "Dummy Prefix"
    }
    Project.objects.get_or_create(id=1, defaults=defaults)

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('timesheets', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_default_othermodel,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='relation',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='user',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timesheetitem',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='timesheetitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='timesheetitem',
            name='item_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('on_call', 'On call'), ('night', 'Night'), ('saturday', 'Saturday'), ('sunday', 'Sunday'), ('other', 'Other')], default='standard', max_length=50, verbose_name='item type'),
        ),
        migrations.AlterField(
            model_name='timesheetitem',
            name='timesheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheets.timesheet', verbose_name='timesheet'),
        ),
        migrations.AlterField(
            model_name='timesheetitem',
            name='worked_hours',
            field=models.FloatField(verbose_name='worked hours'),
        ),
    ]
