# Generated by Django 5.1.6 on 2025-08-02 17:22

import apps.timesheets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0003_timesheet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='month',
            field=models.IntegerField(default=apps.timesheets.models.current_month, verbose_name='month'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='year',
            field=models.IntegerField(default=apps.timesheets.models.current_year, verbose_name='year'),
        ),
    ]
