# Generated by Django 5.1.6 on 2025-08-03 14:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_invoice_line_prefix'),
        ('timesheets', '0004_alter_timesheet_month_alter_timesheet_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timesheet',
            unique_together={('user', 'project', 'month', 'year')},
        ),
    ]
