# Generated by Django 5.1.6 on 2025-08-03 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0005_alter_timesheet_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='name',
        ),
    ]
