# Generated by Django 5.1.6 on 2025-08-03 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0006_remove_timesheet_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='only_weekdays',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='send_reminder',
        ),
    ]
