# Generated by Django 5.1.6 on 2025-08-05 16:26

import apps.timesheets.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0007_remove_timesheet_only_weekdays_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='month',
            field=models.IntegerField(default=apps.timesheets.models.current_month, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='month'),
        ),
    ]
