# Generated by Django 5.2.5 on 2025-10-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0008_alter_timesheet_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetitem',
            name='item_type',
            field=models.IntegerField(choices=[(1, 'Standard'), (2, 'On call'), (3, 'Night'), (4, 'Saturday'), (5, 'Sunday'), (6, 'Other')], default=1, verbose_name='item type'),
        ),
    ]
