# Generated by Django 5.2.5 on 2025-11-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0010_auto_20251020_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeRangeItemTypeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.IntegerField(choices=[(1, 'Standard'), (2, 'On call'), (3, 'Night'), (4, 'Saturday'), (5, 'Sunday'), (6, 'Other')], verbose_name='item type')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeekdayItemTypeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.IntegerField(choices=[(1, 'Standard'), (2, 'On call'), (3, 'Night'), (4, 'Saturday'), (5, 'Sunday'), (6, 'Other')], verbose_name='item type')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
