# Generated by Django 5.2.5 on 2025-11-02 12:40

from django.db import migrations

SQL_TIMERANGE = """
INSERT INTO timesheets_timerangeitemtyperule
SELECT *
FROM telegram_timerangeitemtyperule;
"""

SQL_WEEKDAY = """
INSERT INTO timesheets_weekdayitemtyperule
SELECT *
FROM telegram_weekdayitemtyperule;
"""

class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0011_timerangeitemtyperule_weekdayitemtyperule'),
        ('telegram', '0009_callbackdata_action'),
    ]

    operations = [
        migrations.RunSQL(SQL_TIMERANGE),
        migrations.RunSQL(SQL_WEEKDAY),
    ]
