# Generated by Django 5.1.6 on 2025-02-23 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('relations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(help_text='Address line 1 (eg. dummystreet 42a)', max_length=255)),
                ('line2', models.CharField(blank=True, default='', help_text='Address line 2', max_length=255)),
                ('line3', models.CharField(blank=True, default='', help_text='Address line 3', max_length=255)),
                ('line4', models.CharField(blank=True, default='', help_text='Address line 4', max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('state_province_region', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(choices=[('BE', 'Belgium'), ('NL', 'Netherlands'), ('UK', 'United Kingdom')], default='BE', max_length=10)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relations.relation')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('relation__isnull', False), ('company__isnull', True)), models.Q(('relation__isnull', True), ('company__isnull', False)), _connector='OR'), name='address_must_have_exactly_one_relation_or_company')],
            },
        ),
    ]
