# Generated by Django 5.1.6 on 2025-04-29 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('relations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(help_text='Example: dummystreet 42a', max_length=255, verbose_name='line1')),
                ('line2', models.CharField(blank=True, default='', max_length=255, verbose_name='line2')),
                ('line3', models.CharField(blank=True, default='', max_length=255, verbose_name='line3')),
                ('line4', models.CharField(blank=True, default='', max_length=255, verbose_name='line4')),
                ('postal_code', models.CharField(max_length=20, verbose_name='postal code')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('state_province_region', models.CharField(blank=True, default='', max_length=100, verbose_name='state province region')),
                ('country', models.CharField(choices=[('BE', 'Belgium'), ('NL', 'Netherlands'), ('UK', 'United Kingdom')], default='BE', max_length=10, verbose_name='country')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='company')),
                ('relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relations.relation', verbose_name='relation')),
            ],
            options={
                'verbose_name': 'addresses',
                'verbose_name_plural': 'addresses',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('relation__isnull', False), ('company__isnull', True)), models.Q(('relation__isnull', True), ('company__isnull', False)), _connector='OR'), name='address_must_have_exactly_one_relation_or_company')],
            },
        ),
    ]
