# Generated by Django 5.1.6 on 2025-02-28 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_bankaccount_options_alter_company_options_and_more'),
        ('geo', '0001_initial'),
        ('relations', '0002_alter_relation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Addresses', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=100, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='address',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('BE', 'Belgium'), ('NL', 'Netherlands'), ('UK', 'United Kingdom')], default='BE', max_length=10, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='line1',
            field=models.CharField(help_text='Example: dummystreet 42a', max_length=255, verbose_name='line1'),
        ),
        migrations.AlterField(
            model_name='address',
            name='line2',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='line2'),
        ),
        migrations.AlterField(
            model_name='address',
            name='line3',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='line3'),
        ),
        migrations.AlterField(
            model_name='address',
            name='line4',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='line4'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=20, verbose_name='postal code'),
        ),
        migrations.AlterField(
            model_name='address',
            name='relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relations.relation', verbose_name='relation'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state_province_region',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='state province region'),
        ),
    ]
