# Generated by Django 5.1.6 on 2025-03-01 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_alter_address_options_alter_address_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'addresses', 'verbose_name_plural': 'addresses'},
        ),
    ]
