# Generated by Django 5.1.6 on 2025-04-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('category', models.CharField(choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier')], max_length=50, verbose_name='category')),
                ('language', models.CharField(choices=[('de', 'German'), ('en', 'English'), ('fr', 'French'), ('nl', 'Dutch')], default='en', max_length=10, verbose_name='language')),
                ('phone', models.CharField(blank=True, default='', help_text='Phone number with country code (eg. +32 490 12 34 56)', max_length=255, verbose_name='phone')),
                ('email', models.EmailField(blank=True, default='', max_length=255, verbose_name='email')),
                ('website', models.URLField(blank=True, default='', max_length=255, verbose_name='website')),
                ('vat_number', models.CharField(blank=True, default='', help_text='VAT number', max_length=255, verbose_name='VAT number')),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=255, verbose_name='bank account number')),
            ],
            options={
                'verbose_name': 'relation',
                'verbose_name_plural': 'relations',
            },
        ),
    ]
