# Generated by Django 5.1.6 on 2025-03-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0002_alter_relation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='language',
            field=models.CharField(choices=[('de', 'German'), ('en', 'English'), ('fr', 'French'), ('nl', 'Dutch')], default='en', max_length=10, verbose_name='language'),
        ),
    ]
