# Generated by Django 5.1.6 on 2025-05-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramsettings',
            name='chat_id',
            field=models.IntegerField(unique=True, verbose_name='chat id'),
        ),
    ]
