# Generated by Django 5.1.6 on 2025-06-03 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_alter_telegramsettings_chat_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='error',
            field=models.TextField(blank=True, null=True, verbose_name='error'),
        ),
        migrations.AlterField(
            model_name='message',
            name='raw_message',
            field=models.JSONField(verbose_name='raw message'),
        ),
        migrations.AlterField(
            model_name='telegramsettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
