# Generated by Django 5.2.5 on 2025-08-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_alter_message_error_alter_message_raw_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramsettings',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='data'),
        ),
        migrations.AddField(
            model_name='telegramsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
    ]
