# Generated by Django 5.2.5 on 2025-08-17 22:04

import django.core.serializers.json
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_alter_message_error_alter_message_raw_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramsettings',
            name='data',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='data'),
        ),
        migrations.AddField(
            model_name='telegramsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.CreateModel(
            name='CallbackData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name='token')),
                ('command', models.CharField(max_length=255, verbose_name='command')),
                ('step', models.CharField(max_length=255, verbose_name='step')),
                ('data', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='callback data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'callback data',
                'verbose_name_plural': 'callback data',
                'indexes': [models.Index(models.F('data__correlation_key'), name='callback_correlation_key_idx')],
            },
        ),
    ]
