# Generated by Django 5.2.5 on 2025-08-25 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0004_telegramsettings_data_telegramsettings_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeRangeItemTypeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('standard', 'Standard'), ('on_call', 'On call'), ('night', 'Night'), ('saturday', 'Saturday'), ('sunday', 'Sunday'), ('other', 'Other')], max_length=50, verbose_name='item type')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeekdayItemTypeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('standard', 'Standard'), ('on_call', 'On call'), ('night', 'Night'), ('saturday', 'Saturday'), ('sunday', 'Sunday'), ('other', 'Other')], max_length=50, verbose_name='item type')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
