# Generated by Django 5.2.5 on 2025-10-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0005_timerangeitemtyperule_weekdayitemtyperule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerangeitemtyperule',
            name='item_type',
            field=models.CharField(choices=[(1, 'Standard'), (2, 'On call'), (3, 'Night'), (4, 'Saturday'), (5, 'Sunday'), (6, 'Other')], max_length=50, verbose_name='item type'),
        ),
        migrations.AlterField(
            model_name='weekdayitemtyperule',
            name='item_type',
            field=models.CharField(choices=[(1, 'Standard'), (2, 'On call'), (3, 'Night'), (4, 'Saturday'), (5, 'Sunday'), (6, 'Other')], max_length=50, verbose_name='item type'),
        ),
    ]
