# Generated by Django 5.2.5 on 2025-10-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0006_alter_timerangeitemtyperule_item_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerangeitemtyperule',
            name='item_type',
            field=models.IntegerField(choices=[(1, 'Standard'), (2, 'On call'), (3, 'Night'), (4, 'Saturday'), (5, 'Sunday'), (6, 'Other')], verbose_name='item type'),
        ),
        migrations.AlterField(
            model_name='weekdayitemtyperule',
            name='item_type',
            field=models.IntegerField(choices=[(1, 'Standard'), (2, 'On call'), (3, 'Night'), (4, 'Saturday'), (5, 'Sunday'), (6, 'Other')], verbose_name='item type'),
        ),
    ]
