# Generated by Django 5.2.5 on 2025-10-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0008_auto_20251020_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbackdata',
            name='action',
            field=models.CharField(default='next_step', help_text='Name of a function on the command', max_length=99, verbose_name='action'),
            preserve_default=False,
        ),
    ]
