# Generated by Django 5.2.5 on 2025-11-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0009_callbackdata_action'),
        ('timesheets', '0012_auto_20251102_1240'),
        
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeRangeItemTypeRule',
        ),
        migrations.DeleteModel(
            name='WeekdayItemTypeRule',
        ),
    ]
