name: "Deploy: I Do Accountancy"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p ${{ secrets.DEPLOY_SSH_PORT }} ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Trigger remote deployment
        run: |
          ssh -p ${{ secrets.DEPLOY_SSH_PORT }} {{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} deploy ida
